version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: salemongoDB
    ports:
      - "3002:27017"

  salerestapi:
    image: com.fishmarket/salerestapi
    ports:
      - "8082:8080"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/salemongodb